language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  # Just print out files instead of opening an editor session
  - EDITOR=cat
script:
  # Test that basic functionality doesn't fail
  - ./run_jrnl.py --setup > $HOME/.jrnlrc
  - yes Y | ./run_jrnl.py
  - ./run_jrnl.py grep test
