language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  # Just print out files instead of opening an editor session
  - EDITOR=cat
script:
  # Test that basic functionality doesn't fail
  - ./run_jrnl --setup > $HOME/.jrnlrc
  - yes Y | ./run_jrnl
  - ./run_jrnl grep test
